title: mafevke
description: "I am sharing my opinions and feelings about the things I am interested in!"
author:
  name: "Ege Onur Taga"
  email: "egetaga@gmail.com"
  url: "https://egetaga.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "mafevke"
year : "2021"
